name: test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        group: [1, 2]
    name: parallel group ${{ matrix.group }}/2
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: "Runtime cache: restore"
      uses: actions/cache/restore@v4
      id: cache-restore
      with:
        key: runtime-cache-all
        path: tmp/parallel_runtime_test.log
    - name: rake test # change to `--group-by filesize` when this runtime is missing or bad
      run: bundle exec parallel_test -n 2 --group-by filesize --only-group ${{ matrix.group }} --verbose
      env:
        RECORD_RUNTIME: "true"
    - name: "Runtime cache: clear chunk"
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh extension install actions/gh-actions-cache
        gh actions-cache delete runtime-cache-${{ matrix.group }} --confirm
        mkdir -p tmp/parallel_runtime_test
        mv tmp/parallel_runtime_test.log tmp/parallel_runtime_test/${{ matrix.group }}.log
      continue-on-error: true # do not fail in case the key was deleted by a parallel run
    - name: "Runtime cache: store chunk"
      uses: actions/cache/save@v4
      with:
        key: runtime-cache-${{ matrix.group }}
        path: tmp/parallel_runtime_test
  store-runtime:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: "Runtime cache: load chunk 1"
      uses: actions/cache/restore@v4
      with:
        key: runtime-cache-1
        path: tmp/parallel_runtime_test
    - name: "Runtime cache: load chunk 2"
      uses: actions/cache/restore@v4
      with:
        key: runtime-cache-2
        path: tmp/parallel_runtime_test
    - name: "Runtime cache: combine chunks"
      run: |
        cat tmp/parallel_runtime_test/* > tmp/parallel_runtime_test.log
        cat tmp/parallel_runtime_test.log
    - name: "Runtime cache: clear"
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh extension install actions/gh-actions-cache
        gh actions-cache delete runtime-cache-all --confirm
      continue-on-error: true # do not fail in case the key was deleted by a parallel run
    - name: "Runtime cache: store"
      uses: actions/cache/save@v4
      with:
        key: runtime-cache-all
        path: tmp/parallel_runtime_test.log
